

[platformio]
default_envs = lolin_s2_mini

[env:lolin_s2_mini_saveparam]
platform = espressif32    ;@6.5.0
board = lolin_s2_mini
framework = arduino
board_upload.erase = true
build_src_filter = +<main2.cpp> -<main.cpp>
monitor_speed = 921600
monitor_port = COM4
monitor_filters = send_on_enter, esp32_exception_decoder
upload_protocol = esptool
upload_port = COM4
upload_speed = 921600
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  bblanchon/ArduinoJson@^7.0.0

[env:lolin_s2_mini]
platform = espressif32 ;@ 6.5.0  ;@6.5.0
board = lolin_s2_mini
framework = arduino
board_upload.erase = false
build_src_filter = -<main2.cpp> +<main.cpp>
monitor_speed = 921600
monitor_port = COM4
monitor_filters = send_on_enter, esp32_exception_decoder
upload_protocol = esptool
upload_port = COM4
upload_speed = 921600
; upload_protocol = espota
; upload_port = ESP32S2_Maket
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  fastled/FastLED
  Makuna/NeoPixelBus
  bblanchon/ArduinoJson@^7.0.0
  ESP32Ping
